#' Generate a stratified population of clustered observations
#'
#' Generate a population containing clusters containing healthy and diseased observations
#' generated from normal distributions.
#' The correlated binary data is generated using the multivariate probit method.
#' The correlated continuous marker values are generated by including a random effect
#'
#' @param cluster_size list of cluster sizes per strata
#' @param mean0_strat numeric vector of mean for class label 0 (healthy) for all strata
#' @param mean1_strat numeric vector of mean for class label 1 (diseased) for all strata
#' @param sigma0_strat numeric vector of standard deviation for class label 0 (healthy) for all strata
#' @param sigma1_strat numeric vector of standard deviation for class label 1 (diseased) for all strata
#' @param p1 numeric value for proportion of diseased observations in the population
#' @param corr_mvn numeric value for correlation in multivariate normal distribution
#' @tau numeric value for standard deviation of mixed effect of cluster
#'
#' @return Dataframe containing
#' \itemize{
#'   \item cluster_size: cluster size
#'   \item X: continuous marker values
#'   \item D: class labels (0: healthy; 1: diseased)
#' }
#'
#' @export


generate_pop_clust_strat <- function(cluster_size,
                                      mean0_strat,
                                      mean1_strat,
                                      sigma0_strat,
                                      sigma1_strat,
                                      p1,
                                      corr_mvn = 0.5,
                                      tau = 1) {

  # Checking parameters
  N_strata = length(cluster_size)
  mu0 = as.list(mean0_strat)
  mu1 = as.list(mean1_strat)
  sigma0 = as.list(sigma0_strat)
  sigma1 = as.list(sigma1_strat)

  # Creating dataframe
  pop <-
    purrr::pmap_dfr(list(cluster_size,
                     mu0,
                     mu1,
                     sigma0,
                     sigma1),
                .f = generate_pop_clust,
                corr_mvn = corr_mvn,
                p1 = p1,
                tau = tau,
                .id = "strata") %>%
    mutate(strata = as.numeric(strata),
           cluster_id = as.numeric(cluster_id))

  return(pop)
}
