#' Generate one cluster of binormal distributions
#'
#' Generate one cluster containing healthy and diseased observations generated from normal distributions.
#' The correlated binary data is generated using the multivariate probit method.
#' The correlated continuous marker values are generated by including a random effect
#'
#' @param size_clus size of cluster
#' @param corr_mvn numeric value for correlation in multivariate normal distribution
#' @param mean0 numeric vector of mean for class label 0 (healthy) for all strata
#' @param mean1 numeric vector of mean for class label 1 (diseased) for all strata
#' @param sigma0 numeric vector of standard deviation for class label 0 (healthy) for all strata
#' @param sigma1 numeric vector of standard deviation for class label 1 (diseased) for all strata
#' @param p1 numeric value for proportion of diseased observations in the population
#' @tau numeric value for standard deviation of mixed effect of cluster
#'
#' @return Dataframe containing
#' \itemize{
#'   \item cluster_size: cluster size
#'   \item X: continuous marker values
#'   \item D: class labels (0: healthy; 1: diseased)
#' }
#'
#' @export

genenate_clust <- function(size_clus,
                           corr_mvn,
                           mean0,
                           mean1,
                           sigma0,
                           sigma1,
                           p1,
                           tau){

  # Defining covariance matrix
  cov <- diag(rep(1, size_clus))
  cov[upper.tri(cov)] <- corr_mvn
  cov[lower.tri(cov)] <- corr_mvn

  # Generating multivariate normal
  z <- MASS::mvrnorm(n = 1,
                     mu = rep(0, size_clus),
                     Sigma = cov)

  # Generating binary data
  D <- ifelse(z < qnorm(p1), 1, 0)
  clus_effect <- rnorm(n = 1, sd = tau) # random effect of cluster
  X0 <- rnorm(size_clus, mean0, sigma0)
  X1 <- rnorm(size_clus, mean1, sigma1)

  return(data.frame(cluster_size = size_clus,
                    X = (1-D)*X0 +D*X1 + clus_effect,
                    D = D))
}
