#' Generate a population of clustered observations
#'
#' Generate a population containing clusters containing healthy and diseased observations
#' generated from normal distributions.
#' The correlated binary data is generated using the multivariate probit method.
#' The correlated continuous marker values are generated by including a random effect
#'
#' @param size_clus size of cluster
#' @param mean0 numeric value of mean for class label 0 (healthy)
#' @param mean1 numeric value of mean for class label 1 (diseased)
#' @param sigma0 numeric value of standard deviation for class label 0 (healthy)
#' @param sigma1 numeric value of standard deviation for class label 1 (diseased)
#' @param p1 numeric value for proportion of diseased observations in the population
#' @tau numeric value for standard deviation of mixed effect of cluster
#' @param corr_mvn numeric value for correlation in multivariate normal distribution
#'
#' @return Dataframe containing
#' \itemize{
#'   \item cluster_size: cluster size
#'   \item X: continuous marker values
#'   \item D: class labels (0: healthy; 1: diseased)
#' }
#'
#' @export

generate_pop_clust <- function(cluster_sizes,
                               mean0,
                               mean1,
                               sigma0,
                               sigma1,
                               p1,
                               corr_mvn = 0.5,
                               tau = 1) {

  pop_cluster <-
    cluster_sizes %>%
    purrr::map_dfr(.f = genenate_clust,
                   corr_mvn = corr_mvn,
                   mean0 = mean0,
                   mean1 = mean1,
                   sigma0 = sigma0,
                   sigma1 = sigma1,
                   p1 = p1,
                   tau = tau,
                   .id = "cluster_id")

  return(pop_cluster)

}
